### ISSUE TITLE
jena upgrade

### ISSUE THREAD

**Issue by MarcAgate** [buda-base/lds-pdi#182]
upgrading from Jena 3.12 to 3.14 causes some test units to throw various ClassDefNotFound exceptions, preventing normal deployement on ec2.

**Comment by xristy** [comment]
what classes are not found?

**Comment by MarcAgate** [comment]
java.lang.NoClassDefFoundError: org/apache/jena/tdb/transaction/DatasetGraphTransaction
	at org.apache.jena.tdb.solver.QueryEngineTDB$QueryEngineFactoryTDB.isHandledByTDB(QueryEngineTDB.java:116) ~[jena-tdb-3.10.0.jar:3.10.0]
	at org.apache.jena.tdb.solver.QueryEngineTDB$QueryEngineFactoryTDB.accept(QueryEngineTDB.java:130) ~[jena-tdb-3.10.0.jar:3.10.0]
	at org.apache.jena.sparql.engine.QueryEngineRegistry.find(QueryEngineRegistry.java:97) ~[jena-arq-3.14.0.jar:3.14.0]
	at org.apache.jena.query.QueryExecutionBuilder.build(QueryExecutionBuilder.java:82) ~[jena-arq-3.14.0.jar:3.14.0]
	at org.apache.jena.fuseki.servlets.SPARQLQueryProcessor.createQueryExecution(SPARQLQueryProcessor.java:306) ~[jena-fuseki-core-3.14.0.jar:3.14.0]
	at org.apache.jena.fuseki.servlets.SPARQLQueryProcessor.execute(SPARQLQueryProcessor.java:274) ~[jena-fuseki-core-3.14.0.jar:3.14.0]
	at org.apache.jena.fuseki.servlets.SPARQLQueryProcessor.executeWithParameter(SPARQLQueryProcessor.java:224) ~[jena-fuseki-core-3.14.0.jar:3.14.0]
	at org.apache.jena.fuseki.servlets.SPARQLQueryProcessor.execute(SPARQLQueryProcessor.java:199) ~[jena-fuseki-core-3.14.0.jar:3.14.0]
	at org.apache.jena.fuseki.servlets.ActionService.executeLifecycle(ActionService.java:58) ~[jena-fuseki-core-3.14.0.jar:3.14.0]
	at org.apache.jena.fuseki.servlets.SPARQLQueryProcessor.execGet(SPARQLQueryProcessor.java:79) ~[jena-fuseki-core-3.14.0.jar:3.14.0]
	at org.apache.jena.fuseki.servlets.ActionProcessor.process(ActionProcessor.java:33) ~[jena-fuseki-core-3.14.0.jar:3.14.0]
	at org.apache.jena.fuseki.servlets.ActionBase.process(ActionBase.java:55) ~[jena-fuseki-core-3.14.0.jar:3.14.0]
	at org.apache.jena.fuseki.servlets.ActionExecLib.execAction(ActionExecLib.java:106) ~[jena-fuseki-core-3.14.0.jar:3.14.0]
	at org.apache.jena.fuseki.server.Dispatcher.dispatchAction(Dispatcher.java:113) [jena-fuseki-core-3.14.0.jar:3.14.0]
	at org.apache.jena.fuseki.server.Dispatcher.process(Dispatcher.java:105) [jena-fuseki-core-3.14.0.jar:3.14.0]
	at org.apache.jena.fuseki.server.Dispatcher.dispatch(Dispatcher.java:99) [jena-fuseki-core-3.14.0.jar:3.14.0]
	at org.apache.jena.fuseki.servlets.FusekiFilter.doFilter(FusekiFilter.java:51) [jena-fuseki-core-3.14.0.jar:3.14.0]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642) [jetty-servlet-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533) [jetty-servlet-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1340) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473) [jetty-servlet-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1242) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.Server.handle(Server.java:503) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:364) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260) [jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305) [jetty-io-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103) [jetty-io-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118) [jetty-io-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_201]

**Comment by MarcAgate** [comment]
This fixed the classNotFound exception.


<dependency>
    <groupId>org.apache.jena</groupId>
    <artifactId>jena-tdb</artifactId>
    <version>3.14.0</version>
</dependency>

**Comment by MarcAgate** [comment]
Now having this one related issue: https://github.com/buda-base/jena-stable-turtle/issues/2

**Comment by MarcAgate** [comment]
The deep reason of the failure was coming from jena-turtle-stable using jena-arq 3.11 - I did upgrade it which leads me to then upgrade bdrc-libraries with the new version of jena-turtle-stable. 

Now, ldspdi works with jena 3.14 as of commit 8be4436
